name: Java Application
on:
  push:
    branches: 
      - main
  pull_request: 
    types: [opened, reopened, synchronized]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
        with:
          fetch-depth: 0
      - name: setup jdk 17
        uses: action/setup-java@v3
        with: 
          java-version: 17
