name: Java Application
on:
  push:
    branches:
       - main
  pull_request:
    types: [opened, synchronized, reopened]
jobs:
  build:
    name: Build and Analyze
    runs_on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
       with: 
         fetch-depth: 0 
         
